title: "Archive der kulinarischen Sternenflotte"
description: "Taste the universe — one dish at a time"
baseurl: ""
url: "https://<dein-github-username>.github.io/archive-der-kulinarischen-sternenflotte"
theme: minima
languages: ["de", "en"]

