title: "Archive der kulinarischen Sternenflotte"
description: "Taste the universe — one dish at a time"
baseurl: ""
url: "https://culinarystarfleet.github.io/archive-der-kulinarischen-sternenflotte"
theme: minima
languages: ["de", "en"]
